sudo: false
language: swift
osx_image: xcode8.3
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - XCODE=10
        - IOS_VERSION=12.1
        - TEST_DIR=Swift4
    - os: osx
      env:
        - XCODE=8
        - IOS_VERSION=9.3
        - TEST_DIR=Swift3
before_install:
  - gem install xcpretty
script:
  - ./.travis-build-script.sh
  - ./Tests/${TEST_DIR}/runTest.sh
