sudo: false
language: swift
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - XCODE=10
        - IOS_VERSION=12.1
        - TEST_DIR=Swift4
        - BUILD_PLATFORM=macOS
    - os: osx
      osx_image: xcode8.3
      env:
        - XCODE=8
        - IOS_VERSION=9.3
        - TEST_DIR=Swift3
        - BUILD_PLATFORM=macOS
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages:
            - libcurl4
            - clang
            - libicu-dev
      cache:
        directories:
          - $HOME/swift
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gem install xcpretty; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./.travis-before-linux.sh; fi
script:
  - ./.travis-build-script.sh
  - ./Tests/${TEST_DIR}/runTest.sh
